### ISSUE TITLE
Automapping

### ISSUE THREAD

**Issue by Silveressa** [AlexTheRegent/tld-GameTweaks#3]
In the config file it says:

		autodraw_delay - intervals between automapping 

However underneath in the actual config there's no autodraw map value listed.
What is the proper format to enable this function? 	<autodraw_map value="true"/> ?
Or should the code be formatted differently?

Perhaps just include the line of code in the config with it set to "false" by default so others won't be confused as I am?

**Comment by AlexTheRegent** [comment]
Sorry for late response (it is better to notify me in discord server mentioning me so I will see it way faster).
Config should remain same as in example.
```
...
	<drawing_range value="-1"/>
	<autodraw_delay value="20"/>
...
```
here drawing_range is responsible for drawing range override and autodraw_delay for delays between automatic mapping function in seconds. So with default value="20" it will automap every 20 seconds. If you change this value to 40 (value="40") it will automap every 40'th second.
The only confusion line in config is autodraw_map value in comment - I've removed this variable because it is redundant and can be manipulated via negative autodraw_delay value (for example, <autodraw_delay value="-1">). This way automapping feature will be disabled.

I'm working on adding mod's config to ingame screen + json format so it will be more convenient for users to change values. Plus on adding default game values as default instead of -1.
But idk when I'll be ready to finish it (too many work in cooking tweaks).

**Comment by AlexTheRegent** [comment]
Added ingame settings and default values in 1.0.6 version.
